name: Touch File Hourly

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
#    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Last updated: $(date)" > timestamp.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add timestamp.txt
          git commit -m "Update timestamp"
          git push